--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AshiePleb/SoupFFA
build-by-default: true
branches:
- master
projects:
  SoupFFA:
    path: ""
    lint:
      phpstan: false    
...
