main: Jackaboi\SoupFFA\Main
name: SoupFFA
api: 3.4.1
version: 1.0.0
author: Jackaboi
description: A simple SoupFFA plugin then when you right-click on mushroom soup you regenerate 3 and a half hearts!