main: AshleyHunter01\SoupFFA\Main
name: SoupFFA
api: 3.0.0
version: 1.0.2
author: Jackypoo
description: A simple SoupFFA plugin then when you right-click on soup you regenerate 3 and a half hearts!
