# To enable or disable the plugin in certain worlds, add their names to the 'enabled-worlds' list below. SoupFFA will only work in worlds that are listed.
# You can add as many worlds as you like to the list.

enabled-worlds:
  - world
  - world1
  - world2
  - world3

# This is the amount of health that will be restored when a player drinks a soup.
# The default value is 3.5, which is the same as a golden apple.
health-regen: 3.5

# This is the message that will be displayed to the player when they drink a soup but are already at full health.
full-health-message: "&aYou are already at full health!"

# This is the config version. Do not change this.
# This corresponds to the plugin version.
config-version: 2.1.0